//
// This file is managed by automation. Any changes will be lost.
//

gradle.settingsEvaluated { settings ->
  settings.pluginManagement.repositories {
    clear()
    maven { url = 'https://nexus.gocd.io/repository/internal' }
  }
  settings.dependencyResolutionManagement {
    repositoriesMode = org.gradle.api.initialization.resolve.RepositoriesMode.PREFER_SETTINGS
    repositories {
      maven { url = 'https://nexus.gocd.io/repository/internal' }
    }
  }
}
