[tools]
"java" = "temurin-25"
"ruby" = "4.0"
"node" = "24"

"aqua:aws/aws-cli" = "latest"

# Bootstrapping
"aqua:krallin/tini" = "latest"
"github:gocd-contrib/gocd-golang-bootstrapper" = { version = "latest", bin = "go-agent" }
