#!/usr/bin/env bash

source "${HOME}/.jabba/jabba.sh"

if [ "${JAVA_VERSION}" = "12" ]; then
    jabba use "openjdk@1.12"
elif [ "${JAVA_VERSION}" = "13" ]; then
    jabba use "openjdk@1.13"
else
    jabba use "openjdk@1.11"
fi

exec "$@"
