FROM ubuntu:18.04
MAINTAINER GoCD Team <go-cd-dev@googlegroups.com>

COPY provision /usr/local/src/provision/

RUN /usr/local/src/provision/provision-ubuntu.sh

ENTRYPOINT ["/usr/bin/tini", "--"]

USER go

CMD ["/bin/bash", "-lc", "with-java /bootstrap.sh"]
