FROM centos:6
MAINTAINER GoCD Team <go-cd-dev@googlegroups.com>

COPY provision /usr/local/src/provision/

RUN /usr/local/src/provision/provision.sh

ENTRYPOINT ["/usr/bin/tini", "--"]

USER go

CMD ["/bin/bash", "-lc", "with-java /bootstrap.sh"]
