FROM mcr.microsoft.com/windows/servercore:ltsc2016-amd64
LABEL maintainer="GoCD Team <go-cd-dev@googlegroups.com>"

ENV TMP=c:\\tmp \
    TEMP=c:\\tmp

COPY provision C:\\Users\\ContainerAdministrator\\provision

RUN powershell -File C:\\Users\\ContainerAdministrator\\provision\\provision.ps1

CMD ["powershell", "-File", "C:\\Users\\ContainerAdministrator\\provision\\with-java.ps1", "C:\\go-agent.exe"]
