[tools]
"java" = "microsoft-25"
"node" = { version = "24", postinstall = "corepack enable" }

# Bootstrapping
"github:gocd-contrib/gocd-golang-bootstrapper" = { version = "latest", bin = "go-agent.exe" }
