name             'tini'
maintainer       'ThoughtWorks, Inc.'
maintainer_email 'go-cd-dev@googlegroups.com'
license          'MIT'
description      'Installs/Configures tini'
version          '0.1.0'
