name: Build Windows

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '**/*linux*'
      - '**/*linux*/*'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '**/*linux*'
      - '**/*linux*/*'
  schedule:
    - cron: '0 2 * * FRI' # Run every Friday at 2:00 AM UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: read

env:
  REGISTRY_IMAGE: gocddev/gocd-dev-build
  IMAGE_VERSION: "v3.27"

jobs:
  windows:
    name: ${{ matrix.distro }}
    runs-on: ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { distro: windows-2025, edition: ltsc2025 }
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          flavor: prefix=${{ matrix.distro }}-
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}
            type=sha,prefix=${{ matrix.distro }}-${{ env.IMAGE_VERSION }}-
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@ecb733becfd984bea20b92a4a6af55d5926fa38b # v6.10
        with:
          dockerfile: windowsservercore.Dockerfile
          # no secrets/buildkit support for windows, so have to be content with the ephemeral read-only token being in the layer :(
          buildArgs: "EDITION=${{ matrix.edition }}, GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          labels: ${{ join(fromJSON(steps.meta.outputs.json).labels, ', ') }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ join(fromJSON(steps.meta.outputs.json).tag-names, ', ') }}
          pushImage: ${{ github.event_name != 'pull_request' }}
