name: Build Windows

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '**/*linux*'
      - '**/*linux*/*'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '**/*linux*'
      - '**/*linux*/*'
  schedule:
    - cron: '0 2 * * FRI' # Run every Friday at 2:00 AM UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: read

env:
  REGISTRY_IMAGE: gocddev/gocd-dev-build
  IMAGE_VERSION: "v3.27"

jobs:
  windows:
    name: ${{ matrix.distro }}
    runs-on: ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { distro: windows-2025, edition: ltsc2025 }
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          flavor: prefix=${{ matrix.distro }}-
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}
            type=sha,prefix=${{ matrix.distro }}-${{ env.IMAGE_VERSION }}-
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@19d2beefef6bcdc202195fdcb9deb79a4fab5c1f # v6.8
        with:
          dockerfile: windowsservercore.Dockerfile
          buildArgs: "EDITION=${{ matrix.edition }}"
          labels: ${{ join(fromJSON(steps.meta.outputs.json).labels, ', ') }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ join(fromJSON(steps.meta.outputs.json).tag-names, ', ') }}
          pushImage: ${{ github.event_name != 'pull_request' }}
