[settings]
auto_install = false
ruby.compile = false

[tools]
# Core tools used across many builds
"java" = "temurin-25" # Also Agent runtime JVM
"ruby" = "4.0"
"node" = { version = "24", postinstall = "corepack enable" }
"aws-cli" = { version = "latest", symlink_bins = true }

# Trial installers / test drive
"go" = "1"

# Container Bootstrapping
"aqua:krallin/tini" = "latest"
"github:gocd-contrib/gocd-golang-bootstrapper" = { version = "latest", bin = "go-agent" }
